chore (gha): updated master workflow

diff --git a/.github/workflows/master.yaml b/.github/workflows/master.yaml
--- a/.github/workflows/master.yaml
+++ b/.github/workflows/master.yaml
@@ -20,36 +20,35 @@ concurrency:
 jobs:
     prepare:
         runs-on: ubuntu-latest
-        defaults:
-            run:
-                working-directory: ./frontend
         steps:
-            -   name: Checkout Repository
-                uses: actions/checkout@v4
-            -   name: Detect package manager
-                id: detect-package-manager
-                run: |
-                    if [ -f "${{ github.workspace }}/frontend/yarn.lock" ]; then
-                      echo "manager=yarn" >> $GITHUB_OUTPUT
-                      echo "command=install" >> $GITHUB_OUTPUT
-                      echo "runner=yarn" >> $GITHUB_OUTPUT
-                      exit 0
-                    elif [ -f "${{ github.workspace }}/frontend/package.json" ]; then
-                      echo "manager=npm" >> $GITHUB_OUTPUT
-                      echo "command=ci" >> $GITHUB_OUTPUT
-                      echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-                      exit 0
-                    else
-                      echo "Unable to determine package manager"
-                      exit 1
-                    fi
-            -   name: Setup Node
-                uses: actions/setup-node@v4
-                with:
-                    node-version: '22'
-                    cache: ${{ steps.detect-package-manager.outputs.manager }}
-            -   name: Install dependencies
-                run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+            - name: Checkout Repository
+              uses: actions/checkout@v4
+            - name: Detect package manager
+              id: detect-package-manager
+              run: |
+                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                    echo "manager=yarn" >> $GITHUB_OUTPUT
+                    echo "command=install" >> $GITHUB_OUTPUT
+                    echo "runner=yarn" >> $GITHUB_OUTPUT
+                    exit 0
+                  elif [ -f "${{ github.workspace }}/package.json" ]; then
+                    echo "manager=npm" >> $GITHUB_OUTPUT
+                    echo "command=ci" >> $GITHUB_OUTPUT
+                    echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                    exit 0
+                  else
+                    echo "Unable to determine package manager"
+                    exit 1
+                  fi
+            - name: Setup Node
+              uses: actions/setup-node@v4
+              with:
+                  node-version: '22'
+                  cache: ${{ steps.detect-package-manager.outputs.manager }}
+            - name: Install dependencies
+              run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+            - name: Create environment file
+              run: ./scripts/create-env-file.sh
     lint:
         runs-on: ubuntu-latest
         needs: prepare
@@ -72,8 +71,6 @@ jobs:
             run:
                 working-directory: ./frontend
         steps:
-            - name: Create environment file
-              run: ./../scripts/create-env-file.sh
             - name: Build project
               run: ${{ steps.detect-package-manager.outputs.runner }} npm run build-only
     deploy:
