chore (gha): split jobs for master.yaml workflow
[NO-REF]

diff --git a/.github/workflows/master.yaml b/.github/workflows/master.yaml
--- a/.github/workflows/master.yaml
+++ b/.github/workflows/master.yaml
@@ -90,6 +90,63 @@ jobs:
                   push: true
                   tags: ${{env.DOCKER_USER}}/${{ env.DOCKER_DATABASE_IMAGE_NAME }}:${{ env.TAG_VERSION }},${{env.DOCKER_USER}}/${{ env.DOCKER_DATABASE_IMAGE_NAME }}:lastest
 
+            - name: Inspect Docker Image
+              run: |
+                docker image inspect ${{ env.REGISTRY }}/${{env.DOCKER_USER}}/${{ env.DOCKER_DATABASE_IMAGE_NAME }}:latest
+
+    backend:
+        runs-on: ubuntu-latest
+        needs: database
+        steps:
+            - name: Checkout Repository
+              uses: actions/checkout@v4
+              with:
+                  token: ${{ secrets.SWDBAPP_SSH_PAT }}
+                  submodules: 'recursive'
+
+            - name: Detect package manager
+              id: detect-package-manager
+              run: |
+                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                    echo "manager=yarn" >> $GITHUB_OUTPUT
+                    echo "command=install" >> $GITHUB_OUTPUT
+                    echo "runner=yarn" >> $GITHUB_OUTPUT
+                    exit 0
+                  elif [ -f "${{ github.workspace }}/package.json" ]; then
+                    echo "manager=npm" >> $GITHUB_OUTPUT
+                    echo "command=ci" >> $GITHUB_OUTPUT
+                    echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                    exit 0
+                  else
+                    echo "Unable to determine package manager"
+                    exit 1
+                  fi
+
+            - name: Setup Node
+              uses: actions/setup-node@v4
+              with:
+                  node-version: '22'
+                  cache: ${{ steps.detect-package-manager.outputs.manager }}
+
+            - name: Update NPM
+              run: npm i -g npm
+
+            - name: Install dependencies
+              run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+
+            - name: Login to Docker Hub
+              uses: docker/login-action@v3
+              with:
+                  registry: ${{ env.REGISTRY }}
+                  username: ${{ env.DOCKER_USER }}
+                  password: ${{ env.DOCKER_PASS }}
+
+            - name: Set up QEMU
+              uses: docker/setup-qemu-action@v3
+
+            - name: Set up Docker Buildx
+              uses: docker/setup-buildx-action@v3
+
             - name: Publish Backend Image
               uses: docker/build-push-action@v6
               with:
@@ -99,27 +156,6 @@ jobs:
                   push: true
                   tags: ${{env.DOCKER_USER}}/${{ env.DOCKER_BACKEND_IMAGE_NAME }}:${{ env.TAG_VERSION }},${{env.DOCKER_USER}}/${{ env.DOCKER_BACKEND_IMAGE_NAME }}:lastest
 
-            - name: Inspect Docker Images
+            - name: Inspect Docker Image
               run: |
-                docker image inspect ${{ env.REGISTRY }}/${{env.DOCKER_USER}}/${{ env.DOCKER_DATABASE_IMAGE_NAME }}:latest
                 docker image inspect ${{ env.REGISTRY }}/${{env.DOCKER_USER}}/${{ env.DOCKER_BACKEND_IMAGE_NAME }}:latest
-
-    # deploy_assets:
-    #     runs-on: ubuntu-latest
-    #     needs: lint
-    #     steps:
-    #         - name: Checkout Repository
-    #           uses: actions/checkout@v4
-    #           with:
-    #               token: ${{ secrets.SWDBAPP_SSH_PAT }}
-    #               submodules: 'recursive'
-    #         - name: Install Heroku CLI
-    #           run: |
-    #             curl https://cli-assets.heroku.com/install.sh | sh
-    #         - uses: akhileshns/heroku-deploy@v3.14.15
-    #           with:
-    #             appdir: './www/software/swdbapp/assets'
-    #             usedocker: true
-    #             heroku_api_key: ${{secrets.HEROKU_API_KEY}}
-    #             heroku_app_name: swdbapp-assets
-    #             heroku_email: arturo.martinez@amartinez.dev
