chore (gha): updated to reflect repository changes

diff --git a/.github/workflows/master.yaml b/.github/workflows/master.yaml
--- a/.github/workflows/master.yaml
+++ b/.github/workflows/master.yaml
@@ -18,35 +18,41 @@ concurrency:
     cancel-in-progress: false
 
 jobs:
-    lint:
+    prepare:
         runs-on: ubuntu-latest
         steps:
-            - name: Checkout Repository
-              uses: actions/checkout@v4
-            - name: Detect package manager
-              id: detect-package-manager
-              run: |
-                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-                    echo "manager=yarn" >> $GITHUB_OUTPUT
-                    echo "command=install" >> $GITHUB_OUTPUT
-                    echo "runner=yarn" >> $GITHUB_OUTPUT
-                    exit 0
-                  elif [ -f "${{ github.workspace }}/package.json" ]; then
-                    echo "manager=npm" >> $GITHUB_OUTPUT
-                    echo "command=ci" >> $GITHUB_OUTPUT
-                    echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-                    exit 0
-                  else
-                    echo "Unable to determine package manager"
-                    exit 1
-                  fi
-            - name: Setup Node
-              uses: actions/setup-node@v4
-              with:
-                  node-version: '22'
-                  cache: ${{ steps.detect-package-manager.outputs.manager }}
-            - name: Install dependencies
-              run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+            -   name: Checkout Repository
+                uses: actions/checkout@v4
+            -   name: Detect package manager
+                id: detect-package-manager
+                run: |
+                    if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                      echo "manager=yarn" >> $GITHUB_OUTPUT
+                      echo "command=install" >> $GITHUB_OUTPUT
+                      echo "runner=yarn" >> $GITHUB_OUTPUT
+                      exit 0
+                    elif [ -f "${{ github.workspace }}/package.json" ]; then
+                      echo "manager=npm" >> $GITHUB_OUTPUT
+                      echo "command=ci" >> $GITHUB_OUTPUT
+                      echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                      exit 0
+                    else
+                      echo "Unable to determine package manager"
+                      exit 1
+                    fi
+            -   name: Setup Node
+                uses: actions/setup-node@v4
+                with:
+                    node-version: '22'
+                    cache: ${{ steps.detect-package-manager.outputs.manager }}
+            -   name: Move to frontend folder
+                run: cd frontend
+            -   name: Install dependencies
+                run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+    lint:
+        runs-on: ubuntu-latest
+        needs: prepare
+        steps:
             - name: Check code format
               run: ${{ steps.detect-package-manager.outputs.runner }} npm run format:check
             # - name: Check linting rules
@@ -59,41 +65,8 @@ jobs:
         runs-on: ubuntu-latest
         needs: lint
         steps:
-            - name: Checkout Repository
-              uses: actions/checkout@v4
-            - name: Detect package manager
-              id: detect-package-manager
-              run: |
-                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-                    echo "manager=yarn" >> $GITHUB_OUTPUT
-                    echo "command=install" >> $GITHUB_OUTPUT
-                    echo "runner=yarn" >> $GITHUB_OUTPUT
-                    exit 0
-                  elif [ -f "${{ github.workspace }}/package.json" ]; then
-                    echo "manager=npm" >> $GITHUB_OUTPUT
-                    echo "command=ci" >> $GITHUB_OUTPUT
-                    echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-                    exit 0
-                  else
-                    echo "Unable to determine package manager"
-                    exit 1
-                  fi
-            - name: Setup Node
-              uses: actions/setup-node@v4
-              with:
-                  node-version: '22'
-                  cache: ${{ steps.detect-package-manager.outputs.manager }}
-            - name: Install dependencies
-              run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
             - name: Create environment file
-              run: |
-                  echo "VITE_ASSETS_DIR=../assets" >> .env
-                  echo "VITE_DATA_BANK_API_HOSTNAME=starwars-databank-server.vercel.app/api/v1" >> .env
-                  echo "VITE_DATA_BANK_API_PORT=" >> .env
-                  echo "VITE_DATA_BANK_API_PROTOCOL=https" >> .env
-                  echo "VITE_SW_API_HOSTNAME=swapi.dev/api" >> .env
-                  echo "VITE_SW_API_PORT=" >> .env
-                  echo "VITE_SW_API_PROTOCOL=https" >> .env
+              run: ./scripts/create-env-file.sh
             - name: Build project
               run: ${{ steps.detect-package-manager.outputs.runner }} npm run build-only
             - name: Upload artifact
